// AuditAction.java
package com.commerce_pro_backend.user_identity.enums;

public enum AuditAction {
    // User actions
    USER_CREATED, USER_UPDATED, USER_DELETED, USER_ACTIVATED, USER_DEACTIVATED,
    USER_LOCKED, USER_UNLOCKED, PASSWORD_CHANGED, PASSWORD_RESET, USER_IMPERSONATED,
    
    // Role actions
    ROLE_CREATED, ROLE_UPDATED, ROLE_DELETED, ROLE_ASSIGNED, ROLE_REVOKED,
    PERMISSION_GRANTED, PERMISSION_REVOKED, PERMISSION_CREATED, PERMISSION_UPDATED,
    PERMISSION_DELETED,
    
    // Security actions
    LOGIN_SUCCESS, LOGIN_FAILURE, LOGOUT, SESSION_TERMINATED,
    MFA_ENABLED, MFA_DISABLED, MFA_VERIFIED,
    
    // Configuration
    CONFIG_UPDATED, POLICY_CHANGED,
    
    // Audit
    AUDIT_VIEWED, REPORT_GENERATED, AUDIT_PURGED, AUDIT_EXPORTED
}